// <auto-generated />
namespace RMW.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MembershipRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MembershipRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "201210292251433_MembershipRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
