// <auto-generated />
namespace RMW.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddLog4net : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLog4net));
        
        string IMigrationMetadata.Id
        {
            get { return "201302180456093_AddLog4net"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
